# Site settings
title: "Hyeongmin Choe's Website"
description: "Welcome to Hyeongmin Choe's personal website"
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://hmchoe0528.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
author: "Hyeongmin Choe"
# User settings
username: Hyeongmin Choe
baseurl: ""
user_title: "Graduate Student in SNU Mathematics"
email: sixtail528@snu.ac.kr
# twitter_username: 
github_username:  hmchoe0528
# gplus_username:  

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Google-analytics
# google-analytics:
#  id: "UA-97580319-1"

exclude: ['package.json', 'src' , 'node_modules']
